name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Plugin
        run: ./gradlew buildPlugin

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/distributions/*.zip
          generate_release_notes: true
          fail_on_unmatched_files: true

      - name: Generate updatePlugins.xml
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          TAG=${GITHUB_REF#refs/tags/}
          cat <<EOF > updatePlugins.xml
          <?xml version="1.0" encoding="UTF-8"?>
          <plugins>
            <plugin id="com.whisper3zzz.plugin.ColorBrackets" url="https://github.com/${{ github.repository }}/releases/download/${TAG}/ColorBrackets-${VERSION}.zip" version="${VERSION}">
              <name>ColorBrackets</name>
              <description>
              <![CDATA[
                Rainbow Brackets and Scope Highlight.
                <br>
                See <a href="https://github.com/${{ github.repository }}/releases/tag/${TAG}">release notes</a>.
              ]]>
              </description>
            </plugin>
          </plugins>
          EOF

      - name: Push updatePlugins.xml to main
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git fetch origin main
          git checkout main
          mv updatePlugins.xml updatePlugins.xml.new
          mv updatePlugins.xml.new updatePlugins.xml
          git add updatePlugins.xml
          git commit -m "Update updatePlugins.xml for version ${GITHUB_REF#refs/tags/v}" || echo "No changes to commit"
          git push origin main
